discord:
  # 권장: 봇 토큰 없이 '웹훅 URL'만 사용 (JDA 종료이슈 회피)
  webhook_url: ""
  # 아래 두 값은 webhook_url 비었을 때만 사용
  token: ""
  channel_id: ""
  mention_everyone: false
  mention_role_id: ""

message:
  template: "✨ 전설 포켓몬 스폰! **{name}** (#{dex}) — 월드 {dimension}, 바이옴 {biome}, 좌표 {x} {y} {z}{near}"
  dedupe_seconds: 10

fallback_log_matcher:
  enabled: true
  legendary_line_regex: "^\[Pixelmon\] (?P<name>[A-Za-z'\- ]+) has spawned in a (?P<biome>.+?) biome!$"
  coords_line_regex: "^Spawned (?P<name>[A-Za-z'\- ]+) at: .* x:(?P<x>-?\d+), y:(?P<y>-?\d+), z:(?P<z>-?\d+)$"
