# LegendarySpawnDiscord - config.yml  (Webhook mode recommended)
# Place this file at:  plugins/LegendarySpawnDiscord/config.yml

discord:
  # ✅ Use webhook mode for stability (no bot/JDA needed)
  webhook_url: "PASTE_YOUR_DISCORD_WEBHOOK_URL"
  # If you use webhook mode, keep the next two empty
  token: ""
  channel_id: ""

notify:
  mention_everyone: false
  mention_role_id: ""

# Log fallback watcher (string -> Java regex). SAFE for YAML + Java.
match:
  # e.g. "[Pixelmon] Suicune has spawned in a river biome!"
  legendary_line_regex: '^\[Pixelmon\] (?<name>[A-Za-z''\- ]+) has spawned in a (?<biome>.+?) biome!$'
  # e.g. "Spawned Suicune at: [ world] x: 123, y: 64, z: -45"
  coords_line_regex: '^Spawned (?<name>[A-Za-z''\- ]+) at:.* x:\s*(?<x>-?\d+),\s*y:\s*(?<y>-?\d+),\s*z:\s*(?<z>-?\d+)'

# Duplicate suppression (seconds)
dedupe_seconds: 120
