name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -e -V -DskipTests package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LegendAlert
          path: |
            target/*-shaded.jar
            target/*.jar
