name: build-and-upload-jar
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn -U -B -DskipTests package

      - name: Upload shaded JAR
        uses: actions/upload-artifact@v4
        with:
          name: LegendarySpawnDiscord
          path: |
            target/LegendarySpawnDiscord-*.jar
            !target/*-sources.jar
            !target/*-javadoc.jar
          if-no-files-found: error
          retention-days: 7
